"""
Payment Communities — Bitcoin Micropayment Channels & Lightning Network Protocol.
"""

from payment_communities.anchors import (
    ANCHOR_OUTPUT_SAT,
    create_anchor_commitment_transaction,
    create_anchor_script,
    create_cpfp_fee_bump_transaction,
)
from payment_communities.bitcoin_utils import (
    bytes_to_hex,
    generate_keypair,
    generate_secret,
    hash160,
    hash256,
    hex_to_bytes,
    pubkey_to_p2pkh_address,
    pubkey_to_p2wpkh_address,
    script_to_p2wsh_address,
    sha256,
)
from payment_communities.channel import Channel, ChannelState, HTLCContract
from payment_communities.config import Settings, settings
from payment_communities.contracts import (
    ScriptFactory,
    build_htlc_fulfill_witness,
    build_htlc_refund_witness,
    build_multisig_witness,
    create_2of2_multisig_script,
    create_htlc_script,
    create_p2wsh_scriptPubKey,
)
from payment_communities.core import (
    Err,
    FeePolicy,
    HasSufficientBalance,
    IsChannelOpen,
    IsHTLCActive,
    IsPreimageValid,
    IsTimelockExpired,
    LeaseFeePolicy,
    Ok,
    Result,
    RevocationPolicy,
    RoutingFeePolicy,
    Specification,
    TimelockPolicy,
    handle_domain_errors,
    log_execution,
    retry,
)
from payment_communities.eltoo import (
    EltooState,
    create_eltoo_settlement_transaction,
    create_eltoo_update_transaction,
    validate_eltoo_override,
)
from payment_communities.exceptions import (
    ChannelStateError,
    HTLCExpiredError,
    InsufficientBalanceError,
    InvalidPreimageError,
    PaymentCommunityError,
    RevokedStateBroadcastError,
    RouteNotFoundError,
    ScriptVerificationError,
)
from payment_communities.network import EsploraClient
from payment_communities.node import Node
from payment_communities.ptlc import (
    AdaptorSignature,
    adapt_signature,
    create_adaptor_signature,
    create_ptlc_script,
    create_ptlc_settlement_transaction,
    extract_adaptor_secret,
    verify_adaptor_signature,
)
from payment_communities.revocation import (
    RevocationStore,
    create_breach_remedy_transaction,
    create_revocable_output_script,
    generate_revocation_secret,
)
from payment_communities.routing import (
    DijkstraRoutingStrategy,
    NetworkGraph,
    PaymentRoute,
    RouteHop,
    RoutingStrategy,
    calculate_routing_fee,
)
from payment_communities.sphinx import (
    SphinxPacket,
    SphinxPayload,
    create_onion_packet,
    unwrap_onion_packet,
)
from payment_communities.storage import NetworkState, StorageEngine
from payment_communities.swaps import (
    LiquidityAd,
    SubmarineSwap,
    SwapState,
    SwapType,
    create_submarine_swap_funding_tx,
    create_submarine_swap_script,
)
from payment_communities.transaction import (
    TransactionBuilder,
    create_commitment_transaction,
    create_cooperative_close_transaction,
    create_funding_transaction,
    create_htlc_claim_transaction,
    create_htlc_refund_transaction,
    verify_transaction_witness,
)
from payment_communities.watchtower import (
    WatchtowerDaemon,
    WatchtowerSession,
    decrypt_justice_payload,
    derive_watchtower_hint,
    encrypt_justice_payload,
)

__all__ = [
    "ANCHOR_OUTPUT_SAT",
    "AdaptorSignature",
    "Channel",
    "ChannelState",
    "ChannelStateError",
    "DijkstraRoutingStrategy",
    "EltooState",
    "Err",
    "EsploraClient",
    "FeePolicy",
    "HTLCContract",
    "HTLCExpiredError",
    "HasSufficientBalance",
    "InsufficientBalanceError",
    "InvalidPreimageError",
    "IsChannelOpen",
    "IsHTLCActive",
    "IsPreimageValid",
    "IsTimelockExpired",
    "LeaseFeePolicy",
    "LiquidityAd",
    "NetworkGraph",
    "NetworkState",
    "Node",
    "Ok",
    "PaymentCommunityError",
    "PaymentRoute",
    "Result",
    "RevocationPolicy",
    "RevocationStore",
    "RevokedStateBroadcastError",
    "RouteHop",
    "RouteNotFoundError",
    "RoutingFeePolicy",
    "RoutingStrategy",
    "ScriptFactory",
    "ScriptVerificationError",
    "Settings",
    "Specification",
    "SphinxPacket",
    "SphinxPayload",
    "StorageEngine",
    "SubmarineSwap",
    "SwapState",
    "SwapType",
    "TimelockPolicy",
    "TransactionBuilder",
    "WatchtowerDaemon",
    "WatchtowerSession",
    "adapt_signature",
    "build_htlc_fulfill_witness",
    "build_htlc_refund_witness",
    "build_multisig_witness",
    "bytes_to_hex",
    "calculate_routing_fee",
    "create_2of2_multisig_script",
    "create_adaptor_signature",
    "create_anchor_commitment_transaction",
    "create_anchor_script",
    "create_breach_remedy_transaction",
    "create_commitment_transaction",
    "create_cooperative_close_transaction",
    "create_cpfp_fee_bump_transaction",
    "create_eltoo_settlement_transaction",
    "create_eltoo_update_transaction",
    "create_funding_transaction",
    "create_htlc_claim_transaction",
    "create_htlc_refund_transaction",
    "create_htlc_script",
    "create_onion_packet",
    "create_p2wsh_scriptPubKey",
    "create_ptlc_script",
    "create_ptlc_settlement_transaction",
    "create_revocable_output_script",
    "create_submarine_swap_funding_tx",
    "create_submarine_swap_script",
    "decrypt_justice_payload",
    "derive_watchtower_hint",
    "encrypt_justice_payload",
    "extract_adaptor_secret",
    "generate_keypair",
    "generate_revocation_secret",
    "generate_secret",
    "handle_domain_errors",
    "hash160",
    "hash256",
    "hex_to_bytes",
    "log_execution",
    "pubkey_to_p2pkh_address",
    "pubkey_to_p2wpkh_address",
    "retry",
    "script_to_p2wsh_address",
    "settings",
    "sha256",
    "unwrap_onion_packet",
    "validate_eltoo_override",
    "verify_adaptor_signature",
    "verify_transaction_witness",
]
