from typing import Self

class OpenSSLException(Exception): ...

class CECKey:
    def __init__(self) -> None: ...
    def set_secretbytes(self, secret: bytes) -> None: ...
    def set_pubkey(self, pubkey: bytes) -> None: ...
    def sign(self, hash: bytes) -> bytes: ...
    def verify(self, hash: bytes, sig: bytes) -> bool: ...
    def get_pubkey(self) -> bytes: ...
    @classmethod
    def from_secretbytes(cls, secret: bytes) -> Self: ...
